### ISSUE TITLE
Issue when modifing the key

### ISSUE THREAD

**Issue by bandarudivya** [kaloyan-raev/eclipse-license-management-tools#1]
Hi ,
    Thanks for the eclipse-license-management-tools ,it really helped my need.I have worked on the demo project it worked fine. When i tried to change the  mylicense1-eval.key im getting error.
In addition to this i have few more queries like,
1.Can I change the properties of license key? 
2. Is there any relation between signature key and Expiration Date.
3.When I tried to run with the mylicense1-eval.key, it passes through the method isAuthentic. Sometimes it returns true and sometimes false.

**Comment by kaloyan-raev** [comment]
Nice to see this prototype is useful for you!

The "Signature" property of the license key file is very important. It ensures that the content of the license key cannot be changed by the user. So, if you change anything in the license key file, you need to regenerate the Signature property by signing it again.

Look at the last section in the README: [Create license key files](https://github.com/kaloyan-raev/eclipse-license-management-tools#create-license-key-files)

Does this answer some of your questions?

**Comment by bandarudivya** [comment]
I actually generated a signature key and added it to the properties file but still i'm facing that error. Can you share a document that generates a new signature key and how that new properties file can be added to the eclipse. That can be helpful.

**Comment by kaloyan-raev** [comment]
Did you use the [SignLicense](https://github.com/kaloyan-raev/eclipse-license-management-tools/blob/master/signature/src/signature/SignLicense.java) tool? This the tool you should use instead of trying to manually sign the license key file.

So, you first edit the license key file: changing value of existing properties, or adding new ones. Then you need to sign it with the SignLicense tool, which will automatically add/replace the Signature property.

This is how you use the SignLicense tool:
1. Import the "signature" project in your Eclipse Java IDE.
1. Open the Java Build Path property page of the project and resolve the location to the org.apache.commons.codec.jar
1. Go to > Run > Run Configuration... from the main menu.
1. Create new Java Application configuration.
1. Select the `signature.SignLicense` class file as the Main class.
1. Switch to the Arguments tab.
1. Specify the Program arguments: first - the license key file, second - the private key, e.g. `/home/kraev/git/eclipse-license-management-tools/demo-projects/mylicense1.key /home/kraev/git/eclipse-license-management-tools/demo-projects/mydsa`
1. Hit the Run button.

If the SignLicense tool executes and finish with no output then the license key file is successfully signed.

**Comment by bandarudivya** [comment]
Thankyou so much. It helped me alot. I was giving pub file instead of mylicense key in the argument list.
